import 'package:flutter/material.dart';
import 'package:learn_smart/widgets/my_page.dart';
import 'package:learn_smart/widgets/my_drawer.dart';
import 'package:learn_smart/widgets/text_widget.dart';
import 'package:learn_smart/widgets/app_bar.dart';
import 'package:learn_smart/learn/flutter/flutter_udemy_course/topicsName/flutterCourseTopics.dart';

class FCIntro extends StatefulWidget {
  const FCIntro({Key? key}) : super(key: key);

  @override
  State<FCIntro> createState() => _FCIntroState();
}

class _FCIntroState extends State<FCIntro> {
  @override
  Widget build(BuildContext context) {
    final height = MediaQuery.of(context).size.width / 1.5;
    return Scaffold(
      appBar: const MyAppBar(),
      drawer: MyDrawer(
        activeIndex: 1,
        topicsName: flutterCourseTopics,
        img: 'flutterConceptsI.jpg',
      ),
      body: MyPage(
        children: [
          H1('Intro'),
          H3('What is Flutter?'),
          P('Flutter is actually a combination of two main parts'),
          Li('UI Framework'),
          Li('Collection of Tools'),
          P('It is Single Codebase'),
          P('It is used to create cross platform apps'),
          P('Flutter is not a programming language, dart is a programming language...Flutter use Dart'),
          Note(
              'Whilst you can write the code for all platforms on the same machine, you can only test & run iOS & macOS apps on macOS machine, Windows apps on windows machines and Linux apps on Linux machines!'),
          P('Android and web apps can be built on all operating systems'),
          const H3('Flutter Course Slides'),
          Img(name: 'course-slides-page-001.jpg', height: height),
          Img(name: 'course-slides-page-002.jpg', height: height),
          Img(name: 'course-slides-page-003.jpg', height: height),
          Img(name: 'course-slides-page-004.jpg', height: height),
          Img(name: 'course-slides-page-005.jpg', height: height),
          Img(name: 'course-slides-page-006.jpg', height: height),
          Img(name: 'course-slides-page-007.jpg', height: height),
          Img(name: 'course-slides-page-008.jpg', height: height),
          Img(name: 'course-slides-page-009.jpg', height: height),
          Img(name: 'course-slides-page-010.jpg', height: height),
          Img(name: 'course-slides-page-011.jpg', height: height),
          Img(name: 'course-slides-page-012.jpg', height: height),
          Img(name: 'course-slides-page-013.jpg', height: height),
          Img(name: 'course-slides-page-014.jpg', height: height),
          Img(name: 'course-slides-page-015.jpg', height: height),
          Img(name: 'course-slides-page-016.jpg', height: height),
          Img(name: 'course-slides-page-017.jpg', height: height),
          Img(name: 'course-slides-page-018.jpg', height: height),
          Img(name: 'course-slides-page-019.jpg', height: height),
          Img(name: 'course-slides-page-020.jpg', height: height),
          Img(name: 'course-slides-page-021.jpg', height: height),
          Img(name: 'course-slides-page-022.jpg', height: height),
          Img(name: 'course-slides-page-023.jpg', height: height),
          Img(name: 'course-slides-page-024.jpg', height: height),
          Img(name: 'course-slides-page-025.jpg', height: height),
          Img(name: 'course-slides-page-026.jpg', height: height),
          Img(name: 'course-slides-page-027.jpg', height: height),
          Img(name: 'course-slides-page-028.jpg', height: height),
          Img(name: 'course-slides-page-029.jpg', height: height),
          Img(name: 'course-slides-page-030.jpg', height: height),
          Img(name: 'course-slides-page-031.jpg', height: height),
          Img(name: 'course-slides-page-032.jpg', height: height),
          Img(name: 'course-slides-page-033.jpg', height: height),
          Img(name: 'course-slides-page-034.jpg', height: height),
          Img(name: 'course-slides-page-035.jpg', height: height),
          Img(name: 'course-slides-page-036.jpg', height: height),
          Img(name: 'course-slides-page-037.jpg', height: height),
          Img(name: 'course-slides-page-038.jpg', height: height),
          Img(name: 'course-slides-page-039.jpg', height: height),
          Img(name: 'course-slides-page-040.jpg', height: height),
          Img(name: 'course-slides-page-041.jpg', height: height),
          Img(name: 'course-slides-page-042.jpg', height: height),
          Img(name: 'course-slides-page-043.jpg', height: height),
          Img(name: 'course-slides-page-044.jpg', height: height),
          Img(name: 'course-slides-page-045.jpg', height: height),
          Img(name: 'course-slides-page-046.jpg', height: height),
          Img(name: 'course-slides-page-047.jpg', height: height),
          Img(name: 'course-slides-page-048.jpg', height: height),
          Img(name: 'course-slides-page-049.jpg', height: height),
          Img(name: 'course-slides-page-050.jpg', height: height),
          Img(name: 'course-slides-page-051.jpg', height: height),
          Img(name: 'course-slides-page-052.jpg', height: height),
          Img(name: 'course-slides-page-053.jpg', height: height),
          Img(name: 'course-slides-page-054.jpg', height: height),
          Img(name: 'course-slides-page-055.jpg', height: height),
          Img(name: 'course-slides-page-056.jpg', height: height),
          Img(name: 'course-slides-page-057.jpg', height: height),
          Img(name: 'course-slides-page-058.jpg', height: height),
          Img(name: 'course-slides-page-059.jpg', height: height),
          Img(name: 'course-slides-page-060.jpg', height: height),
          Img(name: 'course-slides-page-061.jpg', height: height),
          Img(name: 'course-slides-page-062.jpg', height: height),
          Img(name: 'course-slides-page-063.jpg', height: height),
          Img(name: 'course-slides-page-064.jpg', height: height),
          Img(name: 'course-slides-page-065.jpg', height: height),
          Img(name: 'course-slides-page-066.jpg', height: height),
          Img(name: 'course-slides-page-067.jpg', height: height),
          Img(name: 'course-slides-page-068.jpg', height: height),
          Img(name: 'course-slides-page-069.jpg', height: height),
          Img(name: 'course-slides-page-070.jpg', height: height),
          Img(name: 'course-slides-page-071.jpg', height: height),
          Img(name: 'course-slides-page-072.jpg', height: height),
          Img(name: 'course-slides-page-073.jpg', height: height),
          Img(name: 'course-slides-page-074.jpg', height: height),
          Img(name: 'course-slides-page-075.jpg', height: height),
          Img(name: 'course-slides-page-076.jpg', height: height),
          Img(name: 'course-slides-page-077.jpg', height: height),
          Img(name: 'course-slides-page-078.jpg', height: height),
          Img(name: 'course-slides-page-079.jpg', height: height),
          Img(name: 'course-slides-page-080.jpg', height: height),
          Img(name: 'course-slides-page-081.jpg', height: height),
          Img(name: 'course-slides-page-082.jpg', height: height),
          Img(name: 'course-slides-page-083.jpg', height: height),
          Img(name: 'course-slides-page-084.jpg', height: height),
          Img(name: 'course-slides-page-085.jpg', height: height),
          Img(name: 'course-slides-page-086.jpg', height: height),
          Img(name: 'course-slides-page-087.jpg', height: height),
          Img(name: 'course-slides-page-088.jpg', height: height),
          Img(name: 'course-slides-page-089.jpg', height: height),
          Img(name: 'course-slides-page-090.jpg', height: height),
          Img(name: 'course-slides-page-091.jpg', height: height),
          Img(name: 'course-slides-page-092.jpg', height: height),
          Img(name: 'course-slides-page-093.jpg', height: height),
          Img(name: 'course-slides-page-094.jpg', height: height),
          Img(name: 'course-slides-page-095.jpg', height: height),
          Img(name: 'course-slides-page-096.jpg', height: height),
          Img(name: 'course-slides-page-097.jpg', height: height),
          Img(name: 'course-slides-page-098.jpg', height: height),
          Img(name: 'course-slides-page-099.jpg', height: height),
        ],
      ),
    );
  }
}
