import 'package:flutter/material.dart';
import 'package:learn_smart/widgets/my_page.dart';
import 'package:learn_smart/widgets/my_drawer.dart';
import 'package:learn_smart/widgets/text_widget.dart';
import 'package:learn_smart/widgets/app_bar.dart';
import 'package:learn_smart/learn/Flutter/Udemy Course/topicsName/flutterCourseTopics.dart';

class FCFoldersDetails extends StatefulWidget {
  const FCFoldersDetails({Key? key}) : super(key: key);

  @override
  State<FCFoldersDetails> createState() => _FCFoldersDetailsState();
}

class _FCFoldersDetailsState extends State<FCFoldersDetails> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: const MyAppBar(),
      drawer: MyDrawer(
        activeIndex: 4,
        topicsName: flutterCourseTopics,
        img: 'flutterConceptsI.jpg',
      ),
      body: const MyPage(
        children: [
          H1('Folders Details'),
          H3('lib'),
          Li('It contains your actual dart code files'),
          H3('.dart-tools'),
          Li('Simply hold some extra configuration for dart tools'),
          H3('.idea'),
          Li('some extra configuration for Android studio'),
          H3('Platform folders'),
          Li('It simply contain platform specific files'),
          Li('build'),
          Li('It contains temporary and output files generated by flutter.'),
          H3('test'),
          Li('Test your main application code, you could define automated test which can be very useful fir catching errors early.'),
          H3('.gitignore'),
          Li('It is a file that\'s used by Git..its managing the code snapshots'),
          H3('.metadata'),
          Li('It is a file that is managed automatically flutter to keep track some internal information'),
          H3('analysis_options.yaml'),
          Li('It is a file that\'s being used by your code editor to show you warnings and errors in your code before ou even run the app which is amazing for catching errors early'),
          Li('And typically, the default settings here'),
          Li('Control warning if you use unused local variables or prefer const'),
          H3('first_app.iml'),
          Li('It is a file that it contains more metadata and information'),
          H3('pubspec.lock'),
          Li('It is connected to this pubspec.yaml file'),
          H3('pubspec.yaml'),
          Li('It used to add third party packages to your flutter projects'),
          H3('README.MD'),
          Li('Simple contains some general information like some description and some resources')
        ],
      ),
    );
  }
}
