import 'package:learn_smart/widgets/code_pro.dart';
import 'package:learn_smart/learn/web/mongo_db/topicsName/mongoDbTopics.dart';

class CreateDatabaseAndCollection extends StatefulWidget {
  const CreateDatabaseAndCollection({Key? key}) : super(key: key);

  @override
  State<CreateDatabaseAndCollection> createState() =>
      _CreateDatabaseAndCollectionState();
}

class _CreateDatabaseAndCollectionState
    extends State<CreateDatabaseAndCollection> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: const MyAppBar(),
      drawer: MyDrawer(
        activeIndex: 2,
        topicsName: mongoDBTopics,
        img: 'mongoDBt.png',
      ),
      body: MyPage(
        children: [
          const H1('Create Database and Collection - MongoDB'),
          const H2('Create a Database:'),
          const P(
              'To create a new database or switch to an existing database, you can use the use command. If the specified database doesn\'t exist, MongoDB will create it when you insert data into it.'),
          const P(
              'Replace youtube with the name of the database you want to create or use. After running this command, you are now working with the youtube database.'),
          Code(title: 'Compass', code: code1, type: 'javascript'),
          const H2('Drop a Database:'),
          const P(
              'To drop a database and permanently remove all its data, you can use the db.dropDatabase() method while connected to the specific database you want to drop. Make sure to be cautious when using this command, as it cannot be undone.'),
          Code(title: 'Compass', code: code2, type: 'javascript'),
          const P(
              'After running this command, the current database (the one you\'re connected to) will be deleted. Make sure you are connected to the correct database before executing this command.'),
          const P(
              'Remember to exercise caution when dropping databases, as this action will result in the loss of all data within the specified database. Always ensure you have backups or data recovery procedures in place as needed'),
          const H2('Show all Databases'),
          const P(
              'To show a list of all the databases in MongoDB, you can use the show dbs command in the MongoDB shell. This command will display a list of all the databases on the MongoDB server, along with their sizes.'),
          Code(title: 'Compass', code: code3, type: 'javascript'),
          const H3('OR'),
          Code(title: 'Compass', code: code4, type: 'javascript'),
          const P(
              'After running this command, MongoDB will display a list of all the databases on the server, along with their sizes in megabytes (MB).'),
          const P(
              'Please note that MongoDB only shows databases that have data in them. If a database is empty (i.e., it doesn\'t contain any collections or documents), it may not appear in the list generated by the show dbs command.'),
          const H2('Create Collection in MongoDB'),
          const P(
              'In MongoDB, you don\'t need to explicitly create a collection before inserting data into it. Collections are created automatically when you insert a document into them. So, if you run the following command:'),
          Code(title: 'Compass', code: code5, type: 'javascript'),
          const P(
              'MongoDB will create a collection named "products" if it doesn\'t already exist, and it will insert the specified document into that collection'),
          const P(
              'After running the insertOne command, you can start querying and working with the "products" collection as it has been created and populated with the document provided'),
          Code(title: 'Compass', code: code6, type: 'javascript'),
          const P(
              'The db.createCollection() method is used to explicitly create a collection with various options, such as setting the maximum size or the documentation validation rules. If you are not specifying these options, you do not need to explicitly create the collection since MongoDB creates new collections when you first store data for the collections'),
          Code(title: 'Compass', code: code7, type: 'javascript'),
          const H3('OR'),
          Code(title: 'Compass', code: code8, type: 'javascript'),
          const H2('Show All Collections:'),
          const P(
              'To list all collections in the current database, you can use the show collections command in the MongoDB shell:'),
          Code(title: 'Compass', code: code9, type: 'javascript'),
          const H3('OR'),
          Code(title: 'Compass', code: code10, type: 'javascript'),
          const H2('Rename a Collection:'),
          const P(
              'In MongoDB, you can use the renameCollection() method to rename a collection. The syntax for renaming a collection is as follows:'),
          Code(title: 'Compass', code: code11, type: 'javascript'),
          const P(
              'n your case, you want to rename the "products" collection to "items". You can do it like this:'),
          Code(title: 'Compass', code: code12, type: 'javascript'),
          const P(
              'This command will rename the "products" collection to "items" in the same database. Please note that you should have the necessary permissions to perform this operation, and it\'s a good practice to ensure that your application code is updated to reflect the new collection name if needed.'),
          const P(
              'Remember that renaming a collection or database should be done with caution, especially in a production environment. Ensure that you have proper backups and that you understand the potential impact on your application before making these changes.'),
          const H2('Drop a Collection:'),
          const P(
              'To drop (delete) a collection in MongoDB, you can use the db.collectionName.drop() method. Replace collectionName with the name of the collection you want to drop. Be cautious when using this command, as it permanently deletes the collection and all its documents.'),
          const P(
              'For example, to drop the "products" collection, you would run:'),
          Code(title: 'Compass', code: code13, type: 'javascript'),
        ],
      ),
    );
  }
}

var code = '''''';
var code13 = '''
db.products.drop()
''';
var code12 = '''
db.products.renameCollection("items")
''';
var code11 = '''
db.oldCollectionName.renameCollection("newCollectionName")
''';
var code10 = '''
show tables
''';
var code9 = '''
show collections
''';
var code8 = '''
db.createCollection( <name>,
  {
    capped: <boolean>,
    timeseries: {                  // Added in MongoDB 5.0
        timeField: <string>,        // required for time series collections
        metaField: <string>,
        granularity: <string>,
        bucketMaxSpanSeconds: <number>,  // Added in MongoDB 6.3
        bucketRoundingSeconds: <number>  // Added in MongoDB 6.3
    },
    expireAfterSeconds: <number>,
    clusteredIndex: <document>,  // Added in MongoDB 5.3
    changeStreamPreAndPostImages: <document>,  // Added in MongoDB 6.0
    size: <number>,
    max: <number>,
    storageEngine: <document>,
    validator: <document>,
    validationLevel: <string>,
    validationAction: <string>,
    indexOptionDefaults: <document>,
    viewOn: <string>,
    pipeline: <pipeline>,
    collation: <document>,
    writeConcern: <document>
  }
)
 ''';
var code7 = '''
db.createCollection("products");
''';
var code6 = '''
db.products.find()
''';
var code5 = '''
db.products.insertOne({"name":"Pen"})
''';
var code4 = '''
show databases
''';
var code3 = '''
show dbs
''';
var code2 = '''
db.dropDatabase()
''';
var code1 = '''
use youtube
''';
